id: I87EFE9A7
default_language: en
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 14:46:46.153176
last_modified: 2023-02-09 14:46:46.153267
source_metadata:
  title: 'PP: Prajñāpāramitāhṛdaya'
  language: en
bases:
  7C3E:
    base_file: 7C3E.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
